#!/bin/sh
# ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
# │ SILVERBULLET - S6 SERVICE SCRIPT                                          │
# ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
# This script is an s6 service run script that launches and manages the
# silverbullet server within the container.
#
# It runs in the FOREGROUND as the silverbullet user.

APP_USER="librarian"
HOME="/home/${APP_USER}"
XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CONFIG_HOME
XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CACHE_HOME
SPACE_DIR="${LIBRARY_SPACE:-${SILVERBULLET_SPACE:-/mnt/volumes/data/space}}"
BIND_ADDR="${LIBRARY_BIND:-${SILVERBULLET_BIND:-0.0.0.0}}"
PORT="${LIBRARY_PORT:-${SILVERBULLET_PORT:-3000}}"
PORT="3000"

# Ensure space directory exists and has correct ownership.
mkdir -p "${SPACE_DIR}"
# chown -R "${APP_USER}:${APP_USER}" "${SPACE_DIR}"

# Export SB_FOLDER for silverbullet to use.
export SB_FOLDER="${SPACE_DIR}"

tail -f /dev/null # 

exec s6-setuidgid "${APP_USER}" \
  /usr/local/bin/silverbullet \
    --hostname "${BIND_ADDR}" \
    --port "${PORT}" \
    "${SPACE_DIR}"
